/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto_EDD1;

/**
 * Ventana que trabaja en conjunto con la lógica del algoritmo de Dijkstra.
 * El usuario seleccionara 2 proteínas en 2 combobox siendo asi como después
 * de pulsar el botón confirmar, se mostrará en el grafo la ruta de menor
 * peso metabólico entre la ProteínaA y la ProteínaB.
 *
 * @author karlg
 */
public class BuscarRutaVentana extends javax.swing.JFrame {
    private org.graphstream.graph.Graph GrafoPrincipal;
    private Interfaz Interfaz;
    private Grafo grafoLogico;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddInteraccionVentana.class.getName());

    /**
     * Creates new form AddInteraccionVentana
     */
    public BuscarRutaVentana(java.awt.Frame parent, boolean modal, org.graphstream.graph.Graph graph, Grafo logico) {
        super("Buscar Ruta Más Corta"); //Le da un nombre a la ventana.
        initComponents();
        setLocationRelativeTo(null); //Coloca la ventana en el centro de la pantalla
        this.GrafoPrincipal = graph;
        this.grafoLogico = logico;
        this.Interfaz = (Interfaz)parent; //Convierte la interfaz principal en la clase padre para poder acceder a sus métodos.
        LlenarCajas();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); //Hace que al cerrar la ventana el programa entero no se cierre.
    }

    /**
     * Método que recibe la información del grafo con los nodos para poder llenar las cajas con las proteínas
     * con el fin de que el usuario pueda elegir las proteínas sin equivocarse.
     */
    private void LlenarCajas(){
        for (org.graphstream.graph.Node n : GrafoPrincipal) {
            CajaRuta1.addItem(n.getId());
            CajaRuta2.addItem(n.getId());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BtnCancelar = new javax.swing.JButton();
        BtnConfirmar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        CajaRuta2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        CajaRuta1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("La ruta mas corta entre ambas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        BtnCancelar.setBackground(new java.awt.Color(51, 51, 51));
        BtnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 110, 40));

        BtnConfirmar.setBackground(new java.awt.Color(51, 51, 51));
        BtnConfirmar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        BtnConfirmar.setText("Confirmar");
        BtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 110, 40));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CajaRuta2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CajaRuta2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(CajaRuta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 90, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hasta");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        CajaRuta1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CajaRuta1.setForeground(new java.awt.Color(255, 255, 255));
        CajaRuta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaRuta1ActionPerformed(evt);
            }
        });
        jPanel2.add(CajaRuta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 90, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ruta más corta de:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 330, 90));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Seleciona dos proteínas para buscar ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Botón que al ser presionado cierra la ventana de selección de interacciones.
     * @param evt 
     */
    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        this.dispose(); //Cierra la ventana
    }//GEN-LAST:event_BtnCancelarActionPerformed

    /**
     * Botón que una vez presionado tomará los datos ingresados y los guardará para mostrarlos en el grafo.
     * Usa el algoritmo de Dijkstra con los datos para poder resaltar y encontrar la ruta más corta entre proteínas.
     * @param evt 
     */
    private void BtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConfirmarActionPerformed
 
        String pA = CajaRuta1.getSelectedItem().toString(); //Obtiene la proteína A
        String pB = CajaRuta2.getSelectedItem().toString(); //Obtiene la proteína B
        
        //Limpia visualmente el grafo, devolviendolo a las configuraciones originales.
        for (org.graphstream.graph.Node n : GrafoPrincipal) n.removeAttribute("ui.class");
        GrafoPrincipal.edges().forEach(e -> e.removeAttribute("ui.class"));
        
        if (pA.equals(pB)) { //Caso en el que el usuario escogió la misma proteína tanto de origen como de destino.
            org.graphstream.graph.Node n = GrafoPrincipal.getNode(pA); //Busca el nodo en el grafo visual.
            if (n != null) n.setAttribute("ui.class", "ruta"); //Lo resalta utilizando la hoja de estilos.
            Interfaz.EscribirInfo("La proteína de origen y destino es la misma: " + pA);
            this.dispose(); //Cierra la ventana.
            return; //Sale del método.
        }
 
        GestorGrafos buscador = new GestorGrafos(grafoLogico.getCantidadProteinas()); //Instancia la herramienta de cálculo con el tamaño del grafo.
        for (int i = 0; i < grafoLogico.getCantidadProteinas(); i++) { //Recorre las proteínas.
            Interaccion[] lista = grafoLogico.getAdyacentes(i); //Obtiene las adyacencias del nodo actual.
            for (int j = 0; j < grafoLogico.getNumAdyacentes(i); j++) { //Recorre las adyacencias
                int destinoIdx = grafoLogico.buscarPorNombre(lista[j].getDestino().getNombre()); //Obtiene el índice del destino.
                int peso = (int)lista[j].getPeso(); //Obtiene el peso de la conexión.
                
                buscador.conectar(i, destinoIdx, peso); //Registra la conexión en el motor de búsqueda de rutas.          
            }
        }
        
        int idxA = grafoLogico.buscarPorNombre(pA); //Convierte el nombre de la proteína origen en un índice numérico.
        int idxB = grafoLogico.buscarPorNombre(pB); //Convierte el nombre de la proteína destino en un índice numérico.
        int[] rastro = buscador.obtenerDistanciasDijkstra(idxA, idxB); // Ejecuta el algoritmo y devuelve un array para reconstruir el camino.
        
        if (rastro[idxB] == -1 && idxA != idxB) { //Caso en que las proteínas seleccionas no tengan una ruta entre ellas.
            Interfaz.EscribirInfo("No existe una ruta biológica entre " + pA + " y " + pB);
            return;
        }

        int actual = idxB; //Empieza desde la proteína de destino para ir hacia atrás hasta el origen.
        
        while (actual != -1) { //Recorre hasta llegar al final.
            String nombreActual = grafoLogico.getProteinas()[actual].getNombre(); // Obtiene el nombre de la proteína actual.
            org.graphstream.graph.Node node = GrafoPrincipal.getNode(nombreActual); //Busca el nodo visualmente.
            if (node != null){ //Pinta el nodo con la hoja de ruta si existe.
                node.setAttribute("ui.class", "ruta");
            }
            
            if (actual == idxA){ //Si llega al origen cierra el ciclo
                break;
            }

            int anterior = rastro[actual]; //Busca la proteína anterior en la ruta más corta.
            
            if (anterior != -1) { //Si existe la proteína anterior entonces:
                String nombreAnterior = grafoLogico.getProteinas()[anterior].getNombre(); //Obtiene el nombre del predecesor.
                // Crea los posibles IDs de la arista.
                String idEdge1 = nombreAnterior + "_" + nombreActual;
                String idEdge2 = nombreActual + "_" + nombreAnterior;
                org.graphstream.graph.Edge edge = GrafoPrincipal.getEdge(idEdge1); //Obtiene la arista visual
                if (edge == null){
                    edge = GrafoPrincipal.getEdge(idEdge2); // Si no existe con el primer ID, prueba con el inverso.
                }
                if (edge != null){
                    edge.setAttribute("ui.class", "ruta"); //Resalta la conexión, cambiando sus propiedades con la hoja de ruta.
                }
            }
            actual = anterior; //Llega al inicio
        }   
        Interfaz.EscribirInfo("Se ha encontrado la ruta metabólica más corta entre proteínas\nRuta más ligera encontrada desde " + pA + " hasta " + pB);
        this.dispose();
    }//GEN-LAST:event_BtnConfirmarActionPerformed

    private void CajaRuta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaRuta1ActionPerformed

    }//GEN-LAST:event_CajaRuta1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnConfirmar;
    private javax.swing.JComboBox<String> CajaRuta1;
    private javax.swing.JComboBox<String> CajaRuta2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
