/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto_EDD1;

/**
 * <p>Ventana encargada de ayudar al usuario a añadir una proteína completamente nueva
 * el usuario escribirá solamente el número de la proteína, el programa lo autocompletara
 * con la letra P para mantener el formato</p>
 * También el usuario tendrá que elegir cuales serán las interacciones de esta proteína
 * y el peso de sus interacciones, si alguno de los espacios no se ha llenado el programa no avanzará.
 * 
 * @author karlg
 */
public class AddProteinaVentana extends javax.swing.JFrame {
    private org.graphstream.graph.Graph GrafoPrincipal;
    private Interfaz Interfaz;
    private Grafo grafoLogico;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddInteraccionVentana.class.getName());

    /**
     * Creates new form AddInteraccionVentana
     */
    public AddProteinaVentana(java.awt.Frame parent, boolean modal, org.graphstream.graph.Graph graph, Grafo logico) {
        super("Añadir nueva Proteína"); //le da un título a la ventana.
        this.GrafoPrincipal = graph;
        this.grafoLogico = logico;
        initComponents();
        setLocationRelativeTo(null); //Coloca la ventana en el centro de la pantalla.
        this.GrafoPrincipal = graph;
        this.Interfaz = (Interfaz)parent; //Convierte la interfaz principal en la clase padre para poder acceder a sus métodos.
        LlenarCajas();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * Método que recibe la información del grafo con los nodos para poder llenar las cajas con las proteínas
     * con el fin de que el usuario pueda elegir que proteína elegir sin equivocarse.
     */
    private void LlenarCajas(){
        for (org.graphstream.graph.Node n : GrafoPrincipal) {
            CajaInteraccion1.addItem(n.getId());
            CajaInteraccion2.addItem(n.getId());
            CajaInteraccion3.addItem(n.getId());
        }
            //Añade a las cajas el item "Ninguna" por si el usuario no quiere que tenga tantas interacciones.        
            CajaInteraccion1.addItem("Ninguna");
            CajaInteraccion2.addItem("Ninguna");
            CajaInteraccion3.addItem("Ninguna");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnCancelar = new javax.swing.JButton();
        BtnConfirmarElim = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        NuevoPeso = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CajaInteraccion3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        CajaInteraccion1 = new javax.swing.JComboBox<>();
        CajaInteraccion2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        NuevaProte = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnCancelar.setBackground(new java.awt.Color(51, 51, 51));
        BtnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 110, 40));

        BtnConfirmarElim.setBackground(new java.awt.Color(51, 51, 51));
        BtnConfirmarElim.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnConfirmarElim.setForeground(new java.awt.Color(255, 255, 255));
        BtnConfirmarElim.setText("Confirmar");
        BtnConfirmarElim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConfirmarElimActionPerformed(evt);
            }
        });
        jPanel1.add(BtnConfirmarElim, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 110, 40));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Peso de sus Interacciones:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        NuevoPeso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NuevoPeso.setForeground(new java.awt.Color(0, 0, 0));
        NuevoPeso.setMinimumSize(new java.awt.Dimension(250, 20));
        NuevoPeso.setOpaque(true);
        NuevoPeso.setPreferredSize(new java.awt.Dimension(80, 20));
        NuevoPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoPesoActionPerformed(evt);
            }
        });
        NuevoPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NuevoPesoKeyTyped(evt);
            }
        });
        jPanel2.add(NuevoPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 340, 70));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Añade una nueva proteína.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Solo escribe el número de la nueva proteína ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        CajaInteraccion3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CajaInteraccion3.setForeground(new java.awt.Color(255, 255, 255));
        CajaInteraccion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaInteraccion3ActionPerformed(evt);
            }
        });
        jPanel1.add(CajaInteraccion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 100, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Interactuará con:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        CajaInteraccion1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CajaInteraccion1.setForeground(new java.awt.Color(255, 255, 255));
        CajaInteraccion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaInteraccion1ActionPerformed(evt);
            }
        });
        jPanel1.add(CajaInteraccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 100, 40));

        CajaInteraccion2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CajaInteraccion2.setForeground(new java.awt.Color(255, 255, 255));
        CajaInteraccion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaInteraccion2ActionPerformed(evt);
            }
        });
        jPanel1.add(CajaInteraccion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 100, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("y selecciona sus primeras 3 interacciones");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("P");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nueva Proteína:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        NuevaProte.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NuevaProte.setForeground(new java.awt.Color(0, 0, 0));
        NuevaProte.setMinimumSize(new java.awt.Dimension(250, 20));
        NuevaProte.setOpaque(true);
        NuevaProte.setPreferredSize(new java.awt.Dimension(80, 20));
        NuevaProte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaProteActionPerformed(evt);
            }
        });
        NuevaProte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NuevaProteKeyTyped(evt);
            }
        });
        jPanel3.add(NuevaProte, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 310, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Botón que al ser presionado cierra la ventana de selección de añadir proteínas.
     * @param evt 
     */
    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        this.dispose(); //Cierra la ventana
    }//GEN-LAST:event_BtnCancelarActionPerformed

    /**
     * Botón que una vez presionado tomará los datos ingresados y los guardará para mostrarlos en el grafo.
     * @param evt 
     */
    private void BtnConfirmarElimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConfirmarElimActionPerformed
 
        //Limpia las propiedades del grafo.
        for (org.graphstream.graph.Node n : GrafoPrincipal) {
            n.removeAttribute("ui.class");
        }
        GrafoPrincipal.edges().forEach(e -> e.removeAttribute("ui.class"));
        
        String ProteInput = NuevaProte.getText().trim(); //Obtiene el número de la proteína insertada.
        String PesoInput = NuevoPeso.getText().trim(); //Obtiene el peso de la proteína.
        
        if (ProteInput.isEmpty()) { //Caso en el que el espacio de la proteína esté vacio.
            Interfaz.EscribirInfo("Por favor, escriba el número de la nueva proteína en el espacio en blanco.");
            return; //Detiene el proceso.
        }
        
        if (PesoInput.isEmpty()) { //Caso en el que el espacio del peso esté vacio.
            Interfaz.EscribirInfo("Por favor escriba el número del peso de la proteína en el espacio en blanco.");
            return; //Detiene el proceso.
        }
    
        String idNueva = "P" + ProteInput; //Completa el nombre de la proteína para agregarle "P" antes del número y mantener el formato.
        
        if (grafoLogico.buscarPorNombre(idNueva) != -1) { //Revisa si la proteína ingresada no existe.
            Interfaz.EscribirInfo("Esta Proteína ya existe.");
            return;
        }
        
        //Obtiene las tres selecciones de las cajas.
        String s1 = CajaInteraccion1.getSelectedItem().toString();
        String s2 = CajaInteraccion2.getSelectedItem().toString();
        String s3 = CajaInteraccion3.getSelectedItem().toString();

        boolean Duplicado = false; //Variable para detectar duplicados en la selección de interacciones.

        if (!s1.equals("Ninguna") && !s1.isEmpty()){ //Revisa si la primera selección es "Ninguna"
            if (s1.equals(s2) || s1.equals(s3)){ //Compara la primera selección con las demás selecciones sin tomar en cuenta "Ninguna"
                Duplicado = true; //Marca como duplicado.
            }
        }
        
        if (!s2.equals("Ninguna") && !s2.isEmpty()){ //Revisa si la segunda selección es "Ninguna"
            if (s2.equals(s3)){ // Compara si es igual a la tercera.
                Duplicado = true; //Marca como duplicado.
            }    
        }
        
        if (Duplicado) { //Si hay duplicados, detener el proceso.
            Interfaz.EscribirInfo("No se puede repetir la misma proteína dos veces");
            return;
        }    
            
        //Crea el nuevo nodo y sus conexiones si no hay mas errores.
        try{           
            
            int PesoFull = Integer.parseInt(PesoInput); //Convierte el peso a número entero
        
            Proteina protNueva = new Proteina(idNueva); //Crea la proteína lógica
            this.grafoLogico.addProteina(protNueva); //Agrega la proteína a la lista del grafo.

            String[] selecciones = {s1, s2, s3}; //Agrupa las selecciones en un arreglo para facilitar el recorrido.
        
            //Crea los enlaces necesarios entre la nueva proteína y las proteínas seleccionadas.
            for (String seleccion : selecciones) { //Recorre las posibles 3 conexiones.
                if (!seleccion.equals("Ninguna") && !seleccion.isEmpty()) {
                    this.grafoLogico.agregarInteraccion(idNueva, seleccion, (double) PesoFull); //Crea el enlace entre la nueva proteína y las seleccionadas.
                }
            }

            Interfaz.EscribirInfo("Se ha añadido la proteína " + idNueva + " con peso de: " + PesoFull);
            this.dispose();

        } catch (Exception e) {
            Interfaz.EscribirInfo("Error al insertar la proteína.");
        }
    }//GEN-LAST:event_BtnConfirmarElimActionPerformed

    private void CajaInteraccion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaInteraccion3ActionPerformed

    }//GEN-LAST:event_CajaInteraccion3ActionPerformed

    private void CajaInteraccion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaInteraccion1ActionPerformed

    }//GEN-LAST:event_CajaInteraccion1ActionPerformed

    private void CajaInteraccion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaInteraccion2ActionPerformed

    }//GEN-LAST:event_CajaInteraccion2ActionPerformed

    private void NuevaProteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaProteActionPerformed

    }//GEN-LAST:event_NuevaProteActionPerformed

    /**
     * Evita que el usuario pueda escribir letras en el cuadro de texto para 
     * elegir el número de la proteína.
     * @param evt 
     */
    private void NuevaProteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NuevaProteKeyTyped

        char c = evt.getKeyChar(); // Captura la tecla presionada.
        
        if (!Character.isDigit(c) && c != java.awt.event.KeyEvent.VK_BACK_SPACE) { //Si la tecla presionada no es un número la borra.
            evt.consume(); //Hace que la letra no aparezca.
            
            
            if (Interfaz != null) {      //Escribe en el cuadro de texto el motivo del error. 
                Interfaz.EscribirInfo("Error: Solo puedes escribir número, no escribas ni letras ni símbolos");
            }
        }
           
    }//GEN-LAST:event_NuevaProteKeyTyped

    private void NuevoPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoPesoActionPerformed

    }//GEN-LAST:event_NuevoPesoActionPerformed

    /**
     * Evita que el usuario pueda escribir letras y símbolos en el cuadro de texto para 
     * elegir el número del peso.
     * @param evt 
     */
    private void NuevoPesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NuevoPesoKeyTyped
        
        char c = evt.getKeyChar(); // Captura la tecla presionada
        
        if (!Character.isDigit(c) && c != java.awt.event.KeyEvent.VK_BACK_SPACE) { //Si la tecla presionada no es un número la borra
            evt.consume();//Hace que la letra no aparezca
            
            if (Interfaz != null) {       //Escribe en el cuadro de texto el motivo del error.
                Interfaz.EscribirInfo("Error: Solo puedes escribir número, no escribas ni letras ni símbolos");
            }
        }
    }//GEN-LAST:event_NuevoPesoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnConfirmarElim;
    private javax.swing.JComboBox<String> CajaInteraccion1;
    private javax.swing.JComboBox<String> CajaInteraccion2;
    private javax.swing.JComboBox<String> CajaInteraccion3;
    private javax.swing.JTextField NuevaProte;
    private javax.swing.JTextField NuevoPeso;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
