/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto_EDD1;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.graphstream.graph.Graph;
import java.awt.Point;
import org.graphstream.ui.view.Viewer;

/**
 * <p>Clase encargada de la interfaz principal. Es lo primero que ve el usuario
 * y con lo que más va a interactuar, posee un botón de cargar archivo al inicio
 * junto con un mensaje de bienvenida, una vez cargado un archivo con éxito los demás
 * botones de la interfaz y el grafo se iniciarán.</p>
 * 
 * @author karlg
 */
public class Interfaz extends javax.swing.JFrame {
    
    private Grafo grafoLogico;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interfaz.class.getName());
    private Graph graph;
    private org.graphstream.graph.Graph grafo;

    /**
     * Creates new form Interfaz
     * Agrega todas las propiedades necesarias a la interfaz para iniciarse, 
     * así como tambien conectarse con la lógica de otras clases.
     */
    public Interfaz() {
        System.setProperty("org.graphstream.ui", "swing");  //Tiene las propiedades para mostrar GraphStream.       
        initComponents();
        this.setTitle("Analizador Biólogico de Proteínas"); //Da un título a la Interfaz.
        this.grafo = new org.graphstream.graph.implementations.SingleGraph("Analizador"); //Crea una nueva forma de interfaz para GraphStream.
        this.grafoLogico = new Grafo(this.grafo, this);
        this.setLocationRelativeTo(null); //Coloca la interfaz en el centro de la pantalla.
        Point p = this.getLocation(); //Consigue la posición de la Interfaz en la pantalla.
        this.setLocation(p.x - 490, p.y); //Mueve la interfaz hacia la izquierda con relación a su posición inicial.
        setVisible(true); //Hace la interfaz visible.
        configurarInterfaz(false); //Hace invisible todos los botones que no sean el botón de cargar, para evitar que se haga otra acción sin antes cargar un grafo.
    }
    
    /**
     * Método para poder escribir en el JTextArea información de otras pantallas.
     * @param mensaje 
     */
    public void EscribirInfo(String mensaje) {
        this.ConsolaTxt.setText(""); //Borra toda la información anterior en el cuadro de texto
        this.ConsolaTxt.setText(mensaje); //Escribe en la consola de la interfaz la nueva información de otras pantallas
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ConsolaTxt = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        BtnCargar = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();
        LabelDetect = new javax.swing.JLabel();
        PanelDeteccion = new javax.swing.JPanel();
        BtnHubs = new javax.swing.JButton();
        BtnEncontrarComp = new javax.swing.JButton();
        BtnRutaCorta = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        PanelDeModificar = new javax.swing.JPanel();
        BtnEliminarProte = new javax.swing.JButton();
        BtnAddProte = new javax.swing.JButton();
        BtnAddIntera = new javax.swing.JButton();
        LabelModi = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BtnLimpiarColores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ConsolaTxt.setEditable(false);
        ConsolaTxt.setBackground(new java.awt.Color(204, 204, 204));
        ConsolaTxt.setColumns(20);
        ConsolaTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ConsolaTxt.setForeground(new java.awt.Color(0, 0, 0));
        ConsolaTxt.setRows(5);
        ConsolaTxt.setText("Bienvenido al Analizador Biológico de Proteinas. \nPor favor, añada un archivo de conexiones para empezar.\n");
        jScrollPane1.setViewportView(ConsolaTxt);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 570, 110));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setForeground(new java.awt.Color(102, 102, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(1505, 115));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnCargar.setBackground(new java.awt.Color(102, 102, 102));
        BtnCargar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnCargar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCargar.setText("Cargar un Archivo");
        BtnCargar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        BtnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCargarActionPerformed(evt);
            }
        });
        jPanel3.add(BtnCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 70));

        BtnGuardar.setBackground(new java.awt.Color(102, 102, 102));
        BtnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        BtnGuardar.setText("Guardar Archivo");
        BtnGuardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });
        jPanel3.add(BtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 130, 70));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 170, 170));

        LabelDetect.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LabelDetect.setForeground(new java.awt.Color(255, 255, 255));
        LabelDetect.setText("Detección de Complejos");
        jPanel1.add(LabelDetect, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));

        PanelDeteccion.setBackground(new java.awt.Color(102, 102, 102));
        PanelDeteccion.setForeground(new java.awt.Color(102, 102, 102));
        PanelDeteccion.setPreferredSize(new java.awt.Dimension(1505, 115));
        PanelDeteccion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnHubs.setBackground(new java.awt.Color(102, 102, 102));
        BtnHubs.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnHubs.setForeground(new java.awt.Color(255, 255, 255));
        BtnHubs.setText("Identificar Hubs");
        BtnHubs.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        BtnHubs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHubsActionPerformed(evt);
            }
        });
        PanelDeteccion.add(BtnHubs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 130, 70));

        BtnEncontrarComp.setBackground(new java.awt.Color(102, 102, 102));
        BtnEncontrarComp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnEncontrarComp.setForeground(new java.awt.Color(255, 255, 255));
        BtnEncontrarComp.setText("<html><center>Encontrar Componentes<br>Proteicos</center></html>");
        BtnEncontrarComp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        BtnEncontrarComp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnEncontrarComp.setMargin(new java.awt.Insets(0, 0, 0, 0));
        BtnEncontrarComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEncontrarCompActionPerformed(evt);
            }
        });
        PanelDeteccion.add(BtnEncontrarComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 70));

        BtnRutaCorta.setBackground(new java.awt.Color(102, 102, 102));
        BtnRutaCorta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnRutaCorta.setForeground(new java.awt.Color(255, 255, 255));
        BtnRutaCorta.setText("Ruta Más Corta");
        BtnRutaCorta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        BtnRutaCorta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRutaCortaActionPerformed(evt);
            }
        });
        PanelDeteccion.add(BtnRutaCorta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 130, 70));

        jPanel1.add(PanelDeteccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 170, 250));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BioGraph");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        PanelDeModificar.setBackground(new java.awt.Color(102, 102, 102));
        PanelDeModificar.setForeground(new java.awt.Color(102, 102, 102));
        PanelDeModificar.setPreferredSize(new java.awt.Dimension(1505, 115));
        PanelDeModificar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnEliminarProte.setBackground(new java.awt.Color(102, 102, 102));
        BtnEliminarProte.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnEliminarProte.setForeground(new java.awt.Color(255, 255, 255));
        BtnEliminarProte.setText("Eliminar Proteínas");
        BtnEliminarProte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        BtnEliminarProte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarProteActionPerformed(evt);
            }
        });
        PanelDeModificar.add(BtnEliminarProte, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 130, 70));

        BtnAddProte.setBackground(new java.awt.Color(102, 102, 102));
        BtnAddProte.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnAddProte.setForeground(new java.awt.Color(255, 255, 255));
        BtnAddProte.setText("Añadir Proteína");
        BtnAddProte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        BtnAddProte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddProteActionPerformed(evt);
            }
        });
        PanelDeModificar.add(BtnAddProte, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 130, 70));

        BtnAddIntera.setBackground(new java.awt.Color(102, 102, 102));
        BtnAddIntera.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnAddIntera.setForeground(new java.awt.Color(255, 255, 255));
        BtnAddIntera.setText("Añadir Interacción");
        BtnAddIntera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        BtnAddIntera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddInteraActionPerformed(evt);
            }
        });
        PanelDeModificar.add(BtnAddIntera, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 70));

        jPanel1.add(PanelDeModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 170, 250));

        LabelModi.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LabelModi.setForeground(new java.awt.Color(255, 255, 255));
        LabelModi.setText("Modificar El Grafo");
        jPanel1.add(LabelModi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Archivo");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        BtnLimpiarColores.setBackground(new java.awt.Color(102, 102, 102));
        BtnLimpiarColores.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnLimpiarColores.setForeground(new java.awt.Color(255, 255, 255));
        BtnLimpiarColores.setText("Limpiar Colores");
        BtnLimpiarColores.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        BtnLimpiarColores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarColoresActionPerformed(evt);
            }
        });
        jPanel1.add(BtnLimpiarColores, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 130, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Botón que al ser presionado llamará a la lógica de la clase Grafo,
     * específicamente el método obtenerHubPrincipal() que se encarga
     * de identificar y resaltar los Hubs.
     * @param evt 
     */
    private void BtnHubsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHubsActionPerformed

        this.grafoLogico.obtenerHubPrincipal();
   
    }//GEN-LAST:event_BtnHubsActionPerformed
 
    /**
     * <p>Botón que trabaja en conjunto con el método cargarArchivo() de la clase
     * GestorDeArchivos.</p>
     * Abre el JFileChooser para seleccionar el archivo .csv que contiene las conexiones necesarias
     * para el grafo, cuando el archivo .csv sea cargado con éxito, se habilitarán los demás
     * botones de la interfaz, con el fin de evitar que sean pulsados sin antes cargar un archivo.
     * @param evt 
     */
    private void BtnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCargarActionPerformed
       
        JFileChooser selector = new JFileChooser(); //Abre la ventana de selección de archivos.
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos CSV", "csv"); //Hace por predeterminado que solo se visualicen los archivos con terminación .csv
        selector.setFileFilter(filtro); 
        
        if (selector.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) { //Verifica si el usuario selecciono el archivo correcto.
            File archivoSeleccionado = selector.getSelectedFile(); //Obtiene el archivo seleccionado.

            try {
                this.grafo.clear(); //Reinicia el grafo.
                Estilo(); //Aplica los estilos predeterminados de la hoja de estilos del grafo.
                this.grafoLogico = new Grafo(this.grafo, this); //Instancia una nueva estructura de control para manejar los datos que están por leerse.
                
                GestorDeArchivos gestor = new GestorDeArchivos(this); //llama a la lógica de la clase GestorDeArchivos.
                boolean exito = gestor.cargarArchivo(archivoSeleccionado.getAbsolutePath(), this.grafoLogico);
                if (exito) {
                    mostrarYPosicionarGrafo(); //Llama al método encargado de la visualización del grafo.
                    configurarInterfaz(true); //Se vuelve true para poder cambiar los valores de visualización de los botones de la interfaz.
                    this.ConsolaTxt.setText("Archivo Cargado Con éxito.");
                }else {
                    configurarInterfaz(false); //En caso de que no se haya podido cargar el archivo no se muestran los demás botones de la interfaz.
                    this.ConsolaTxt.setText("Error: Terminación del archivo incorrecto.");
                }
         
            }catch (Exception e) {
                configurarInterfaz(false); //En caso de otros errores, no se muestran los demás botones de la interfaz.
                this.ConsolaTxt.setText("Error al cargar el archivo.");
            }
        }

    }//GEN-LAST:event_BtnCargarActionPerformed
   
    /**
     * Método que funciona como una palanca de activación, recibe información al cargar un archivo.
     * Si el archivo se cargó correctamente, todos los botones se activaran y funcionaran para poder
     * interactuar con el grafo, de lo contrario permaneceran apagados e invisibles.
     * @param estado 
     */
    private void configurarInterfaz(boolean estado) {
        
        //Activación y aparición de cada uno de los botones de la interfaz una vez cargado el archivo correcto.                  
        BtnAddIntera.setVisible(estado);
        BtnAddProte.setVisible(estado);
        BtnGuardar.setVisible(estado);
        BtnEliminarProte.setVisible(estado);
        BtnEncontrarComp.setVisible(estado);
        BtnRutaCorta.setVisible(estado);
        BtnHubs.setVisible(estado);
        PanelDeModificar.setVisible(estado);
        PanelDeteccion.setVisible(estado);
        LabelModi.setVisible(estado);
        LabelDetect.setVisible(estado);
        BtnLimpiarColores.setVisible(estado);
    }
        
    /**
     * Método encargado de mover la visualización del Graphstream a la derecha de la pantalla
     * obteniendo su posición inicial y desplazandola a la derecha
     */
    private void mostrarYPosicionarGrafo() {
        Viewer viewer = grafo.display(); //Muestra el grafo.
        javax.swing.SwingUtilities.invokeLater(() -> { //Espera a que el grafo se dibuje para poder ejecutar lo que sigue.
            try {
                java.awt.Component view = (java.awt.Component) viewer.getDefaultView(); //Obtiene el componente visual para poder trabajar con el grafo como si fuera un objeto.
                java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(view); //Busca donde se ubica el grafo cargado.
                if (win != null) { 
                    java.awt.Point p = win.getLocation(); //Guarda las coordenadas iniciales del grafo
                    win.setLocation(p.x + 290, p.y); //Desplaza las coordenadas obtenidas 290 pixeles a la derecha.
                }
            }catch (Exception e) { 
                this.ConsolaTxt.setText("Error al mover el grafo.");
            }
        });
    }

    /**
    * <p>Hoja de estilos para el Graphstream para cambiar las propiedades de los nodos
    * y de sus apuntadores.</p>
    * Los cambios se aplican al momento de iniciar  el Graphstream y después de realizar acciones de resaltar nodos.
    */
    public void Estilo(){
        String estiloGrafo =
                
                //Cambia las propiedades de todo lo que tiene que ver con los nodos.
                "node {" + 
                "fill-color: lightblue;" + //Color del nodo.
                "size: 60px;" + //Tamaño del nodo.
                "stroke-mode: plain;" + //Borde del nodo.
                "stroke-color: black;" + //Color del borde.
                "stroke-width: 2px;" + //Ancho del borde del nodo.
                "text-size: 16px;" + //Tamaño del texto dentro de los nodos.
                "}" +
                
                //Cambia las propiedades de los apuntadores entre nodos.
                "edge {" +                
                "size: 2px;" +  //Cambia el grosor de la línea   
                "text-size: 20px;" + //Tamaño del texto en los apuntadores que en este caso es el peso.
                "text-background-mode: rounded-box;" + //Le coloca un fondo blanco al peso para que se pueda diferenciar, sin este los números no se perciben dentro de las interacciones.
                "}" +        
                
                //Trabaja con el identificador de Hubs para poder resaltar el nodo con mayor conexiones.
                "node.hub {" +
                "fill-color: red;" + //Modifica solo el color del hub principal.
                "size: 75px;" + //Hace el hub más grande para que se note.
                "stroke-mode: plain;" + //Borde del Hub.
                "stroke-width: 3px;" + //Tamaño del borde.
                "}"  +
                
                //Trabaja con el algoritmo de Dijkstra para resaltar visualmente la ruta de menos peso en el grafo.
                "node.ruta {" +
                "fill-color: orange;" + //Color de los nodos que forman parte de la ruta.
                "size: 70px;" + //Tamaño de los nodos resaltados un poco más grande que los demás.
                "}" +                       
                "edge.ruta {" + //Cambia el color de los apuntadores de la ruta.
                "fill-color: darkorange;" +        
                "}" +
                
                //Aplica color a los diferentes componentes conexos para no repetir colores y se vea más ordenado.
                "node.comp1 { fill-color: lightgreen; }" + 
                "node.comp2 { fill-color: yellow; }" + 
                "node.comp3 { fill-color: lightpurple; }" + 
                "node.comp4 { fill-color: pink; }" + 
                "node.comp5 { fill-color: gray; }";   

        this.grafo.setAttribute("ui.stylesheet", estiloGrafo); //Aplica los atributos al grafo.
        this.grafo.setAttribute("layout.force", 0.1); //Separa los nodos para que no se vean tan juntos.
    }

    /**
     * Botón que llama al método obtenerBFS() de la clase GestorGrafos
     * y que resalta visualmente cuales son los componentes conexos 
     * con diferentes colores para cada grupo de proteínas.
     * @param evt 
     */
    private void BtnEncontrarCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEncontrarCompActionPerformed
        
        try {
            //Limpia visualmente los cambios del grafo.
            for (org.graphstream.graph.Node n : grafo){
                n.removeAttribute("ui.class");
            }
            grafo.edges().forEach(e -> e.removeAttribute("ui.class"));
            
            //Sincroniza la clase GestorGrafo con el estado actual del grafo en caso de modificaciones.
            int nTotal = grafoLogico.getCantidadProteinas(); //Cuantas proteínas hay en total.
            if (nTotal == 0){ //Si no hay datos entonces el proceso se detiene.
                return;
            } 
            
            GestorGrafos gestor = new GestorGrafos(nTotal); //Crea una nueva herramienta de cálculo para manejar la cantidad que haya de nodos.
            
            for (int i = 0; i < nTotal; i++) { //Recorre cada proteína
                Interaccion[] ady = grafoLogico.getAdyacentes(i); //Obtiene la lista de proteínas conectadas a ese nodo.
                for (int j = 0; j < grafoLogico.getNumAdyacentes(i); j++) {
                    int dest = grafoLogico.buscarPorNombre(ady[j].getDestino().getNombre()); //Busca el índice de la proteína conectada para poder usarla.
                    gestor.conectar(i, dest, (int)ady[j].getPeso()); //Crea el enlace en la estructura lógica.
                    gestor.conectar(dest, i, (int)ady[j].getPeso()); //Se hace dos veces de esta forma para asegurar la bidireccionalidad.
                    if (dest != -1) { //Verifica que el nodo destino realmente exista en el registro.
                        gestor.conectar(i, dest, (int)ady[j].getPeso()); //Registra la conexión de ida en el gestor de cálculos.
                        gestor.conectar(dest, i, (int)ady[j].getPeso()); //Registra la conexión de vuelta para asegurar que el grafo sea no dirigido.
                    }
                }
            }
            
            int[] mapaComponentes = gestor.obtenerBFS(); //Ejecuta el BFS (Búsqueda de anchura).
            int maxComp = 0; //Almacena el número total de grupos encontrados.
            for (int id : mapaComponentes){ //Busca cuál es el número de grupo más alto para saber cuántos grupos existen en total.
                if (id > maxComp){
                    maxComp = id;
                }
            } 
       
            for (int i = 0; i < nTotal; i++) { //Ciclo para aplicar cabios visuales a las proteínas involucradas.
                String nombre = grafoLogico.getProteinas()[i].getNombre(); //Obtiene el nombre de la proteína.
                org.graphstream.graph.Node node = grafo.getNode(nombre); //Busca el nodo de la proteína en Graphstream.
                
                if (node != null) {
                    int idComp = mapaComponentes[i]; //Obtiene el número de grupo al que pertenece esta proteína.
                    
                    //Aplica colores diferentes a cada componente conexo hasta un máximo de 5, después de eso los colores serán los iniciales.
                    if (idComp <= 5) {
                        node.setAttribute("ui.class", "comp" + idComp);
                    }else {
                        node.setAttribute("ui.class", "node"); //Se aplica el color que se le aplica a nodos iniciales en caso de que hayan muchos grupos conexos.
                    }
                }
            }

            //Generación de un reporte textual que se imprimirá en la consola de la interfaz.
            String reporte = "Análisis de complejos proteicos completado.\n";
            reporte += "Se han detectado " + maxComp + " grupos aislados.\n\n";
            
            for (int c = 1; c <= maxComp; c++) { //Recorre cada uno de los grupos encontrados.
                reporte += "Grupo #" + c + ": ";
                for (int i = 0; i < nTotal; i++) { //Revisa toda la lista de proteínas.
                    if (mapaComponentes[i] == c) { // Si la proteína pertenece al grupo actual, agrega el nombre de la proteína al reporte.
                        reporte += grafoLogico.getProteinas()[i].getNombre() + " ";
                    }
                }
                reporte += "\n";    //Salto de línea.                    
            }
            EscribirInfo(reporte); //Escribe el reporte en la consola.
            
        }catch (Exception e) {
            EscribirInfo("Error al identificar componentes conexos.");
        }
    }//GEN-LAST:event_BtnEncontrarCompActionPerformed

    /**
     * Abre una nueva ventana que puede modificar el grafo en donde el usuario 
     * podrá elegir que proteína eliminar junto con sus interacciones.
     * @param evt 
     */
    private void BtnEliminarProteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarProteActionPerformed
    
        EliminarProteinaVentana ventana = new EliminarProteinaVentana(this, true, this.grafo, this.grafoLogico); //Pasa los 4 parámetros a la nueva ventana que se abrirá.
        ventana.setVisible(true); //Hace la ventana visible.
    }//GEN-LAST:event_BtnEliminarProteActionPerformed

    /**
     * Abre una nueva ventana  que puede modificar el grafo en donde el usuario 
     * puede añadir una proteína completamente nueva,
     * indicando sus conexiones y peso.
     * @param evt 
     */
    private void BtnAddProteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddProteActionPerformed
        
        AddProteinaVentana ventana = new AddProteinaVentana(this, true, grafo, this.grafoLogico); //Pasa los 4 parámetros a la nueva ventana que se abrirá.
        ventana.setVisible(true); //Hace la ventana visible.

    }//GEN-LAST:event_BtnAddProteActionPerformed

    /**
     * Abre una nueva ventana la cual le pedirá al usuario indicar una ruta
     * entre dos proteínas conectadas para calcular la ruta más corta entre ambas.
     * @param evt 
     */
    private void BtnRutaCortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRutaCortaActionPerformed
        
        BuscarRutaVentana ventana = new BuscarRutaVentana(this, true, this.grafo, this.grafoLogico); //Pasa los 4 parámetros a la nueva ventana que se abrirá.
        ventana.setVisible(true); //Hace la ventana visible.
    }//GEN-LAST:event_BtnRutaCortaActionPerformed

    /**
     * <p>Botón que muestra el JFileChooser para poder guardar un nuevo archivo de terminación .csv
     * que contenga los cambios realizados al grafo.</p>
     * Trabaja con el método guardarArchivo() de la clase GestorDeArchivos.
     * @param evt 
     */
    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        
        JFileChooser selector = new JFileChooser(); //Abre la ventana de selección de archivos de JFileChooser.
        selector.setDialogTitle("Guardar cambios en el archivo"); //Da un título a la ventana.
        
        if (selector.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) { //Verifica que opción eligió el usuario dentro de la ventana.
            File archivoDestino = selector.getSelectedFile(); //Obtiene el objeto tipo archivo que el usuario seleccionó o nombró.
            String ruta = archivoDestino.getAbsolutePath(); //Consigue la ruta de donde se guardó el archivo
            
            if (!ruta.toLowerCase().endsWith(".csv")) { //Verifica si el nombre del archivo no tiene la terminación .csv ignorando las mayúsculas.
                ruta += ".csv"; //Si no tiene la terminación esta se le agrega al final para asegurar el formato.
            } 
            GestorDeArchivos gestor = new GestorDeArchivos(this); //Instancia la clase encargada de manejar la entrada y salida de datos.
            gestor.guardarArchivo(ruta, this.grafoLogico); //Llama al método que recorre los datos.
        }
    }//GEN-LAST:event_BtnGuardarActionPerformed

    /**
     * Abre una nueva ventana de modificación de grafo que se encarga de 
     * preguntarle al usuario cual será la nueva interacción a añadir, 
     * indicando también su peso.
     * @param evt 
     */
    private void BtnAddInteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddInteraActionPerformed
        
        AddInteraccionVentana ventana = new AddInteraccionVentana(this, true, grafo, this.grafoLogico); //Pasa los 4 parámetros a la nueva ventana que se abrirá.
        ventana.setVisible(true); //Hace la ventana visible.
    }//GEN-LAST:event_BtnAddInteraActionPerformed
  
    /**
     * Botón que al ser presionado regresa las modificaciones visuales como 
     * el tamaño o el color de los nodos a sus propiedades originales.
     * @param evt 
     */
    private void BtnLimpiarColoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarColoresActionPerformed
        
        for (org.graphstream.graph.Node n : grafo){ //Limpia los nodos.
                n.removeAttribute("ui.class");
        }
        grafo.edges().forEach(e -> e.removeAttribute("ui.class")); //Limpia los apuntadores.
        EscribirInfo("Vizualización reiniciada.");
    }//GEN-LAST:event_BtnLimpiarColoresActionPerformed

    /**
     * <p>Clase Main</p>
     * Cuando el programa sea ejecutado lo primero que se iniciara será la interfaz
     * en la cual solo se podrá cargar un archivo antes de empezar.
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interfaz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddIntera;
    private javax.swing.JButton BtnAddProte;
    private javax.swing.JButton BtnCargar;
    private javax.swing.JButton BtnEliminarProte;
    private javax.swing.JButton BtnEncontrarComp;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnHubs;
    private javax.swing.JButton BtnLimpiarColores;
    private javax.swing.JButton BtnRutaCorta;
    private javax.swing.JTextArea ConsolaTxt;
    private javax.swing.JLabel LabelDetect;
    private javax.swing.JLabel LabelModi;
    private javax.swing.JPanel PanelDeModificar;
    private javax.swing.JPanel PanelDeteccion;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
