/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto_EDD1;

/**
 * Ventana encargada de obtener del usuario que proteínas desea que tengan 
 * una nueva interacción a partir de unas Combobox con todas las proteínas disponibles
 * en el grafo, adicional de también especificar que peso tendrá esa interacción,
 * si no se completan esos dos requisitos la interacción no se añadira.
 * 
 * @author karlg
 */
public class AddInteraccionVentana extends javax.swing.JFrame {
    private org.graphstream.graph.Graph GrafoPrincipal;
    private Interfaz Interfaz;
    private Grafo grafoLogico;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddInteraccionVentana.class.getName());

    /**
     * Creates new form AddInteraccionVentana
     */
    public AddInteraccionVentana(java.awt.Frame parent, boolean modal, org.graphstream.graph.Graph graph, Grafo logico) {
        super("Añadir Interacción"); //Le da un nombre a la ventana.
        initComponents();
        setLocationRelativeTo(null); //Coloca la ventana en el centro de la pantalla.
        this.GrafoPrincipal = graph;
        this.grafoLogico = logico;
        this.Interfaz = (Interfaz)parent; //Convierte la interfaz principal en la clase padre para poder acceder a sus métodos.
        LlenarCajas();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); //Hace que al cerrar la ventana el programa entero no se cierre.
    }

    /**
     * Método que recibe la información del grafo con los nodos para poder llenar las cajas con las proteínas
     * con el fin de que el usuario pueda elegir que interacción agregar sin equivocarse.
     */
    private void LlenarCajas(){
        for (org.graphstream.graph.Node n : GrafoPrincipal) {
            Caja1.addItem(n.getId());
            Caja2.addItem(n.getId());
        }
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BtnCancelar = new javax.swing.JButton();
        BtnConfirmar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PesoInteraccion = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        Caja2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Caja1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Selecciona su peso");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        BtnCancelar.setBackground(new java.awt.Color(51, 51, 51));
        BtnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 110, 40));

        BtnConfirmar.setBackground(new java.awt.Color(51, 51, 51));
        BtnConfirmar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        BtnConfirmar.setText("Confirmar");
        BtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 110, 40));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Peso de la interacción:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        PesoInteraccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PesoInteraccion.setForeground(new java.awt.Color(0, 0, 0));
        PesoInteraccion.setMinimumSize(new java.awt.Dimension(250, 20));
        PesoInteraccion.setOpaque(true);
        PesoInteraccion.setPreferredSize(new java.awt.Dimension(80, 20));
        PesoInteraccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesoInteraccionActionPerformed(evt);
            }
        });
        PesoInteraccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PesoInteraccionKeyTyped(evt);
            }
        });
        jPanel2.add(PesoInteraccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 350, 70));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Caja2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Caja2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(Caja2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 90, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Interactua Con");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        Caja1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Caja1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(Caja1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 350, 70));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Seleciona dos proteínas para que interactuen");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Botón que al ser presionado cierra la ventana de selección de nuevas interacciones.
     * @param evt 
     */
    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        this.dispose(); //Cierra la ventana
    }//GEN-LAST:event_BtnCancelarActionPerformed

    /**
     * Botón que una vez presionado tomará los datos ingresados y 
     * los guardará para mostrarlos en el grafo, cerrando la ventana.
     * @param evt 
     */
    private void BtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConfirmarActionPerformed

        //Limpia los atributos del grafo.
        for (org.graphstream.graph.Node n : GrafoPrincipal){
            n.removeAttribute("ui.class");
        }
        GrafoPrincipal.edges().forEach(e -> e.removeAttribute("ui.class"));
        
        //Obtención de los datos ingresados en los campos correspondientes.
        String p1 = Caja1.getSelectedItem().toString();
        String p2 = Caja2.getSelectedItem().toString();
        String PesoInput = PesoInteraccion.getText().trim();
        
        //Situación de caso en que el usuario no escriba el peso de la interacción en el cuadro en blanco
        if (PesoInput.isEmpty()) {
            Interfaz.EscribirInfo("Por favor, escriba el peso de la interacción en el espacio en blanco.");
            return;
        }
      
        //Situación de caso en que las dos proteínas sean iguales.
        if (p1.equals(p2)){
            Interfaz.EscribirInfo("No se puede crear una interacción entre una proteína y ella misma.");
            return;
        }       
        
        try{ //Bloque para construir texto a número
            int Peso = Integer.parseInt(PesoInput); //Convierte el texto del peso a un número entero.
            
            if (Peso <= 0) { //Situación de caso en que el peso sea 0
                Interfaz.EscribirInfo("El peso debe ser un número mayor a 0");
                return;
            }

            boolean exito = this.grafoLogico.agregarInteraccion(p1, p2, (double) Peso); //Guarda la conexión en la lógica del grafo
            if(exito){
                Interfaz.EscribirInfo("Interacción añadida con éxito");
                this.dispose(); //Cierra la ventana
            }
        }catch(NumberFormatException e){
            Interfaz.EscribirInfo("Error al añadir la interacción");       
        }
        
    }//GEN-LAST:event_BtnConfirmarActionPerformed

    private void PesoInteraccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesoInteraccionActionPerformed

    }//GEN-LAST:event_PesoInteraccionActionPerformed

    /**
     * Método que evita que el usuario escriba en el campo del peso algún símbolo
     * o letra, eliminandolo y garantizando que el usuario escriba únicamente números.
     * @param evt 
     */
    private void PesoInteraccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PesoInteraccionKeyTyped
        
        char c = evt.getKeyChar(); // Captura la tecla presionada.
        
        if (!Character.isDigit(c) && c != java.awt.event.KeyEvent.VK_BACK_SPACE) { //Si la tecla presionada no es un número la borra.
            evt.consume();//Hace que la letra no aparezca
            
            if (Interfaz != null) { //Escribe en el cuadro de texto el motivo del error.
                Interfaz.EscribirInfo("Solo puedes escribir número, no escribas ni letras ni símbolos");
            }
        }
    }//GEN-LAST:event_PesoInteraccionKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnConfirmar;
    private javax.swing.JComboBox<String> Caja1;
    private javax.swing.JComboBox<String> Caja2;
    private javax.swing.JTextField PesoInteraccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
