/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto_EDD1;

/**
 * Ventana encargada de modificar el grafo eliminando la proteína que el usuario 
 * elija mediante una combobox, una vez selaccionada la proteína esta se eliminara
 * del grafo y quedará guardado.
 * 
 * @author karlg
 */
public class EliminarProteinaVentana extends javax.swing.JFrame {
    private org.graphstream.graph.Graph GrafoPrincipal;
    private Interfaz Interfaz;
    private Grafo grafoLogico;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddInteraccionVentana.class.getName());

    /**
     * Creates new form AddInteraccionVentana
     */
    public EliminarProteinaVentana(java.awt.Frame parent, boolean modal, org.graphstream.graph.Graph visual, Grafo logico) {
        super("Eliminar Proteína"); //Le da un nombre a la ventana
        initComponents();
        setLocationRelativeTo(null); //Coloca la ventana en el centro de la pantalla.
        this.GrafoPrincipal = visual;
        this.grafoLogico = logico;
        this.Interfaz = (Interfaz)parent; //Convierte la interfaz principal en la clase padre para poder acceder a sus métodos.
        LlenarCajas();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); //Evita qeu cuando se cierre la ventana se cierre el programa entero
    }

    /**
     * Método que recibe la información del grafo con los nodos para poder llenar las cajas con las proteínas
     * con el fin de que el usuario pueda elegir que proteina elegir sin equivocarse.
     */
    private void LlenarCajas(){
        for (org.graphstream.graph.Node n : GrafoPrincipal) {
            Caja.addItem(n.getId());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BtnCancelar = new javax.swing.JButton();
        BtnConfirmarElim = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Caja = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Selecciona la proteína que quieras eliminar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        BtnCancelar.setBackground(new java.awt.Color(51, 51, 51));
        BtnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 110, 40));

        BtnConfirmarElim.setBackground(new java.awt.Color(51, 51, 51));
        BtnConfirmarElim.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnConfirmarElim.setForeground(new java.awt.Color(255, 255, 255));
        BtnConfirmarElim.setText("Confirmar");
        BtnConfirmarElim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConfirmarElimActionPerformed(evt);
            }
        });
        jPanel1.add(BtnConfirmarElim, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 110, 40));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Caja.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Caja.setForeground(new java.awt.Color(255, 255, 255));
        Caja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaActionPerformed(evt);
            }
        });
        jPanel2.add(Caja, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 130, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Botón que al ser presionado cierra la ventana de selección de eliminar proteínas.
     * @param evt 
     */
    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        this.dispose(); //Cierra la ventana.
    }//GEN-LAST:event_BtnCancelarActionPerformed

    /**
     * Botón que una vez presionado tomará los datos ingresados eliminará la 
     * proteína correspondiente junto con sus interacciones
     * y lo guardará para mostrarlos en el grafo.
     * @param evt 
     */
    private void BtnConfirmarElimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConfirmarElimActionPerformed

        //Devuelve los atributos visuales del grafo a su estado original.
        for (org.graphstream.graph.Node n : GrafoPrincipal){
            n.removeAttribute("ui.class");
        }
        GrafoPrincipal.edges().forEach(e -> e.removeAttribute("ui.class"));
               
        Object seleccion = Caja.getSelectedItem(); //Consigue la proteína seleccionada en la caja de selección.
        
        String idNodo = seleccion.toString(); //Convierte el objeto seleccionado al nombre de la proteína.
        
        this.grafoLogico.eliminarProteina(idNodo); //Borra el rastro de todas las aristas relacionadas a ese nodo con la lógica.
        Interfaz.EscribirInfo("La proteína "+ idNodo + " y sus conexiones han sido eliminadas con éxito");
        this.dispose(); //Cierra la ventana       
    }//GEN-LAST:event_BtnConfirmarElimActionPerformed

    private void CajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaActionPerformed

    }//GEN-LAST:event_CajaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnConfirmarElim;
    private javax.swing.JComboBox<String> Caja;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
